// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmgrseqvrarrfcyurlwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZ3JzZXF2cmFycmZjeXVybHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDE3OTEsImV4cCI6MjA2MzMxNzc5MX0.Y5VShFM1v0GvlGq8d2hJf_axmVSLAkA7sHG_sHQE_n8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);